#!/usr/bin/env bash

if [ "x${1}" == "xmod" ]; then
    GO111MODULE=on
    msgenv="GO111MODULE=on "
    flags= -mod vendor
else
    flags=
fi

echo cleaning
go clean -v

echo building \`${msgenv}go build -v${flags} srv.go\` \> srv.exe

go build -v${flags} srv.go
#  && echo running && ./$(basename $PWD)
cp -f srv.exe /c/Users/tfwro/Desktop/DesktopMess/.git-react/react-fomantic
